# Base image
FROM node:19-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies for production build
RUN npm ci --only=production

# Copy source files
COPY ./src ./src

# Expose the API port
EXPOSE 3001
# Start the API server
CMD ["npm", "start"]