version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./src:/app/src
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
