version: '3'
services:
  app:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_REFRESH_CRONTAB="*/30 * * * *"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./src:/app/src
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
