name: Run tests
run-name: ${{ github.actor }} triggered quality check pipeline
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main
      - dev

env:
  SLACK_WEBHOOK_URL: "${{ secrets.SLACK_WEBHOOK_URL}}"
  SLACK_CHANNEL: "${{ secrets.GITHUBACTIONS_SLACK_CHANNEL }}"

jobs:
  testing:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: |-
      ${{
         github.ref_name == 'dev' && 'dev'
      || github.base_ref == 'dev' && 'dev'
      ||                             'release'
      }}

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        id: setupnode
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: NPM install
        id: npminstall
        run: "npm install"

      - name: Setup env
        id: setupenv
        run: "cp env.example .env"

      - name: Run testing
        id: unittest
        run: "npm run test:gh"

      - name: Run Notification
        id: runnotificationsent
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: ${{ env.SLACK_CHANNEL }}
          message: Running CI tests on {{ env.GITHUB_REF_NAME }} branch ${{ job.status }}
        if: always()
